spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/thietbi247"
    username: root
    password: root

  ai:
    openai:
      api-key: ${GEMINI_KEY}
      chat:
        base-url: https://generativelanguage.googleapis.com
        completions-path: /v1beta/openai/chat/completions
        options:
          model: gemini-2.0-flash

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8080
  servlet:
    context-path: /thietbi247

jwt:
  signer_key: "RQgYbW4isolFJRmxEhJJDSmW3mgZ9Qmg1CNpnMnzwQTmsSc0WWBxH7NuY8Q40DR6"

